spring:
  application:
    name: server-zuul
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serverUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8062
endpoints:
  sensitive: false
zuul:
  #commodity-service不自动生成路由配置，如果写'*'，会忽略掉所有服务的自动路由配置
  ignored-services: 'commodity-servuce'
  #所有的服务请求路径以/api做前缀
  prefix: /api
  #/commodity/**的所有请求，转发给commodity-service服务。
  routes:
    commodity-service: '/commodity/**'

#设置hystrix默认超时时间为3秒
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
#设置commodity-service应用的hystrix超时时间为2秒
#hystrix.command.commodity-service.execution.isolation.thread.timeoutInMilliseconds: 2000
#设置ribbon的全局超时时间为7秒
#ribbon.ReadTimeout: 7000
#设置commodity-service应用的ribbon的超时时间为6秒
#commodity-service.ribbon.ReadTimeout: 6000
# 开启重试
#zuul.retryable=true
#spring.cloud.loadbalancer.retry.enabled=true
# 请求连接的超时时间
#ribbon.connectTimeout=2000
# 请求处理的超时时间
#ribbon.readTimeout=5000
# 对当前实例的重试次数
#ribbon.maxAutoRetries=1
# 切换实例的重试次数
#ribbon.maxAutoRetriesNextServer=3
# 对所有操作请求都进行重试
#ribbon.okToRetryOnAllOperations=true
