server:
  port: 8012

spring:
  application:
    name: SONA-GATEWAY
  #令牌桶算法使用的redis
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          #开启服务列表发现并拥有默认路由功能，true开启，false关闭，默认就是false，以下三行也可以删除或者注释
          enable: true
          #开启小写验证，默认feign根据服务名查找都是用的全大写
          lowerCaseServiceId: true
      routes:
        # sona-order 服务过滤规则
        - id: sona-order
        # 转发的后的地址前缀
          uri: lb://sona-order
        # 需要转发的地址
          predicates:
            - Path=/order/createOrder
          filters:
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultFallback
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@pathKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
#服务降级配配置
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 2000
#注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8010/eureka/

# log日志配置
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug


