spring:
  application:
    name: sona-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    gateway:
      discovery:
        locator:
          #接入注册中心
          enabled: true
          #开启小写验证，默认feign根据服务名查找都是用的全大写
          lowerCaseServiceId: true
      routes:
        - id: sona-product
          # 转发的后的地址前缀
          uri: http://localhost:8082
         # uri: lb://sona-product
          # 需要转发的地址
          predicates:
            - Path=/product/**

        - id: sona-order
          # 转发的后的地址前缀
          uri: lb://sona-order
          # 需要转发的地址
          predicates:
            - Path=/order/**
server:
  port: 8011


#注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka/
